version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-2020}:2020"
    environment:
      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
      - PUBLIC_URL=${PUBLIC_URL}
      - PORT=${PORT:-2020}
    restart: unless-stopped
